version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      time: "07:30"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      time: "07:30"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      time: "07:30"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "docker"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      time: "07:30"
      timezone: "Asia/Tokyo"
