\i sql/create/CreateUsersTable.sql
\i sql/create/CreatePasswordResetTokensTable.sql
\i sql/create/CreateMAATokensTable.sql
\i sql/create/CreatePlansTable.sql
\i sql/create/CreateDaysTable.sql
\i sql/create/CreateGooglePlacesTable.sql
\i sql/create/CreateGooglePlaceTypesTable.sql
\i sql/create/CreateGoogleTypeAssociationsTable.sql
\i sql/create/CreateTransportationsType.sql
\i sql/create/CreatePlacesTable.sql
\i sql/create/CreatePackingsTable.sql
