\i sql/drop/DropPackingsTable.sql
\i sql/drop/DropPlacesTable.sql
\i sql/drop/DropTransportationsTable.sql
\i sql/drop/DropGoogleTypeAssociationsTable.sql
\i sql/drop/DropGooglePlaceTypesTable.sql
\i sql/drop/DropGooglePlacesTable.sql
\i sql/drop/DropDaysTable.sql
\i sql/drop/DropPlansTable.sql
\i sql/drop/DropMAATokensTable.sql
\i sql/drop/DropPasswordResetTokensTable.sql
\i sql/drop/DropUsersTable.sql